version: 2.1

jobs:
  debian-cloud-image:
    machine:
      image: ubuntu-2204:current
    resource_class: large
    steps:
      - checkout
      - run:
          name: Install build dependencies
          command: |
            sudo apt update -y
            sudo apt install -y libguestfs-tools qemu-utils wget curl zstd
      - run:
          name: Download image
          command: |
            wget https://cloud.debian.org/images/cloud/trixie/latest/debian-13-genericcloud-amd64.qcow2 -O debian-13-genericcloud-amd64.qcow2

      - run:
          name: Prepare debian.sources file
          command: |
            # TUNA mirror in DEB822
            cat << 'EOF' > debian.sources
            Types: deb
            URIs: https://mirrors.tuna.tsinghua.edu.cn/debian
            Suites: trixie trixie-updates trixie-backports
            Components: main contrib non-free non-free-firmware
            Signed-By: /usr/share/keyrings/debian-archive-keyring.gpg

            Types: deb
            URIs: https://security.debian.org/debian-security
            Suites: trixie-security
            Components: main contrib non-free non-free-firmware
            Signed-By: /usr/share/keyrings/debian-archive-keyring.gpg
            EOF

      - run:
          name: Customize Debian 13 image
          command: |
            export DEBIAN_FRONTEND=noninteractive
            export LIBGUESTFS_BACKEND=direct
            sudo dpkg-statoverride --update --add root root 0644 /boot/vmlinuz-$(uname -r)
            sudo usermod -aG kvm $USER
            sudo chown $USER /dev/kvm
            virt-customize -a debian-13-genericcloud-amd64.qcow2 \
              --smp 1 --verbose \
              --timezone "Asia/Shanghai" \
              --append-line "/etc/default/grub:# disables OS prober to avoid loopback detection which breaks booting" \
              --append-line "/etc/default/grub:GRUB_DISABLE_OS_PROBER=true" \
              --run-command "update-grub" \
              --run-command "systemctl enable serial-getty@ttyS1.service" \
              --append-line "/etc/systemd/timesyncd.conf:NTP=time.apple.com time.windows.com" \
              --run-command "sed -i 's|generate_mirrorlists: true|generate_mirrorlists: false|g' /etc/cloud/cloud.cfg.d/01_debian_cloud.cfg" \
              --delete "/etc/apt/sources.list" \
              --delete "/etc/apt/sources.list.d/debian.sources" \
              --upload debian.sources:/etc/apt/sources.list.d/debian.sources \
              --update --install "unzip,ssh,git,nano,wget,curl,jq,ca-certificates,rename,net-tools,tar,debian-keyring,debian-archive-keyring,apt-transport-https,qemu-guest-agent,spice-vdagent,axel,sudo,bash-completion,most,screen,less,bzip2,zstd" \
              --run-command "apt-get -y autoremove --purge && apt-get -y clean" \
              --delete "/root/install-docker.sh" \
              --delete "/var/log/*.log" \
              --delete "/var/lib/apt/lists/*" \
              --delete "/var/cache/apt/*" \
              --truncate "/etc/machine-id"
      - run:
          name: Compress image artifact
          command: |
            zstd -T0 -10 debian-13-genericcloud-amd64.qcow2 -o debian-13-genericcloud-amd64-customized.qcow2.zst

      - store_artifacts:
          path: debian-13-genericcloud-amd64-customized.qcow2.zst
          destination: debian-13-genericcloud-amd64-customized.qcow2.zst

workflows:
  version: 2
  build:
    jobs:
      - debian-cloud-image
